services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-store-db
    env_file:
      - ../.env
    volumes:
      - store_data:/var/lib/postgresql/data
      - ../db/init_tables.sql:/docker-entrypoint-initdb.d/init_table.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
     - "5432:5432"
    restart: always
    networks:
      - database-transfer
  consul:
    image: hashicorp/consul
    container_name: consul-service
    ports:
      - "8500:8500"
    restart: always
    networks:
      - consul-networks
  
  crud-service:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: crud-service
    environment:
      - CONFIG_PATH=/service/.env
    env_file:
      - ../.env
    depends_on:
      postgres-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: always
    networks:
      - database-transfer
      - consul-networks
      
volumes:
  store_data:
networks:
  database-transfer:
    driver: bridge
  consul-networks:
    driver: bridge